---
title: "Hello, Penguins!"
author: "mother nature"
format: 
  revealjs:
    logo: images/quarto-logo.png
    footer: "My Footer"
    chalkboard: TRUE
editor: visual
editor_options: 
  chunk_output_type: console
---

::: notes
:::

# Introduction

## Data

For this analysis we'll use the penguins dataset from the palmerpenguins R package.

```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(ggthemes)
library(palmerpenguins)
library(gt)
```

## Species

The figure below is a scatterplot of species of penguins.

```{r}
#| label: bill-dims-species
#| warning: false
#| fig-width: 5
#| fig-asp: 0.618
#| echo: true 
#| output-location: column-fragment

ggplot(data = penguins,
       mapping = aes(x = bill_length_mm, 
                     y = bill_depth_mm,
                     color = species,
                     shape = species)) +
  geom_point() +
  scale_color_colorblind() +
  labs(x = "Bill length (mm)", y = "Bill depth (mm)") +
  theme_minimal()
```

## Penguins

The table below shows the first 10 penguins from the dataset.

```{r}
#| label: penguins-top10

penguins |>
  slice_head(n = 10) |>
  select(species, island, bill_length_mm, bill_depth_mm) |>
  gt()
```

# Analysis

::: incremental
-   bullet 1

-   bullet 2
:::

# References
